### ISSUE TITLE
Pofficium.pl: Invalid script function Benedicamus Domino.

### ISSUE THREAD

**Issue by Geremia** [DivinumOfficium/divinum-officium-website#2] opened 2017-02-23 17:47 UTC
I get this error in my server's logs:

Pofficium.pl: Invalid script function Benedicamus Domino. at divinum-officium-website/web/cgi-bin/horas/horascommon.pl line 1864.

[Line 1864](https://github.com/DivinumOfficium/divinum-officium-website/blob/master/web/cgi-bin/horas/horascommon.pl#L1864) is:

    return dispatch_script_function($function_name, @args);

**Comment by gregordick** [comment] 2017-02-24 00:01
Thanks.  I couldn't reproduce, but it's probably fixed in divinum-officium 700778b.

**Closed by gregordick** 2017-02-24 00:01 UTC
